Hospital_Management_System/Controllers/NursesManagmentController.cs
using demo.Models;
using Hospital_Management_System.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hospital_Management_System.Controllers
{
    [Authorize(Roles = "Admin")]
    public class NursesManagmentController : Controller
	{
		HMSEntites _context = new HMSEntites();
		public ActionResult Index()
		{
			//full name and department --details->(update-delete)
			var data =
	   from s in _context.Staffs
	   join dept in _context.Departments 
	   on s.dept_id equals dept.Id
	   join n in _context.Nurses 
	   on s.ID equals n.Id
	   select new StaffVM
	   {
		   Name = s.FullName,
		   DeptName = dept.Name,
		   Id = n.Id,
	   };
			List<StaffVM> result = data.ToList();

			return View("Index", result);
		}
		public ActionResult NurseDetails(int id)
		{

			var data =
		  from s in _context.Staffs
		  join n in _context.Nurses
		  on s.ID equals id
		  join dept in _context.Departments
		  on s.dept_id equals dept.Id
		  select new StaffDetailsVM
		  {
			  Id = id,
			  FullName = s.FullName,
			  Gender = s.Gender,
			  BDate = s.BDate,
			  Phone = s.Phone,
			  Role = s.Role,
			  UserName = s.UserName,
			  Specialization = n.Specialization,
			  DepartmentName = dept.Name,
			  Qualifications = s.Qualifications,
			  Governorate = s.Governorate,
			  City = s.City
		  };



			return View("NurseDetails", data.ToList().FirstOrDefault());
		}
	}
}

Hospital_Management_System/Controllers/StatisticsController.cs
using Microsoft.AspNetCore.Mvc;
using demo.Models;
using Hospital_Management_System.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MySqlConnector;
using System.Data;
using System.Linq;
using System.Numerics;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Hospital_Management_System.Controllers
{
	public class StatisticsController : Controller
	{
		HMSEntites context = new HMSEntites();
		public IActionResult Index()
		{
			List<StatisticsHospitalVM> statistics = new();

			statistics.Add(GetGenderRisk("Common Cold"));
			statistics.Add(GetDoctorAppointmentCount(91, 12));
			statistics.Add(GetGovernorateDiseaseCount("Bani Suef"));
			statistics.Add(GetDeathCount());
			statistics.Add(GetAvgAgeByDiagnosis());
			statistics.Add(GetDepartmentPatientCount());
			statistics.Add(GetMostCommonDiagnosis());
			statistics.Add(GetTopTreatments());
			statistics.Add(GetAverageSalary());
			statistics.Add(BloodTypeStatistics());
			statistics.Add(GetDashboardStatistics());
			return View(statistics);
		}

		private StatisticsHospitalVM GetDoctorAppointmentCount(int doctorId, int month)
		{
			var query = from a in context.Appointments
						join s in context.Staffs on a.Doctor_id equals s.ID
						where s.ID == doctorId && a.Date.Month == month
						group a by s.FullName into doctorGroup
						select new StatisticsHospitalVM
						{
							DoctorFullName = doctorGroup.Key,
							AppointmentCount = doctorGroup.Count()
						};
            return query.FirstOrDefault();
		}
		private StatisticsHospitalVM GetAverageSalary()
		{
			double averageSalary = context.Staffs
				.Average(s => s.Salary);

			return new StatisticsHospitalVM
			{
				AverageSalary = averageSalary
			};
		}
		private StatisticsHospitalVM BloodTypeStatistics()
		{
			var topBloodType = context.Patients
				.Join(context.MedicalRecords, p => p.ID, mr => mr.Patient_id, (p, mr) => new { p, mr })
				.Where(joined => joined.mr.Diagnosis == "Migraine")
				.GroupBy(joined => joined.p.Blood_Type)
				.Select(group => new StatisticsHospitalVM
				{
					BloodType = group.Key,
					PatientCount = group.Count()
				})
				.OrderByDescending(result => result.PatientCount)
				.FirstOrDefault();

			return topBloodType;
		}
		private StatisticsHospitalVM GetGenderRisk(string diagnosis)
		{
			var query = from p in context.Patients
						join mr in context.MedicalRecords on p.ID equals mr.Patient_id
						where mr.Diagnosis == diagnosis
						group p by p.Gender into genderGroup
						orderby genderGroup.Count() descending
						select new StatisticsHospitalVM
						{
							Gender = genderGroup.Key,
							RiskCount = genderGroup.Count()
						};

			return query.FirstOrDefault();
		}

		private StatisticsHospitalVM GetGovernorateDiseaseCount(string governorate)
		{
			var query = from m in context.MedicalRecords
						join p in context.Patients on m.Patient_id equals p.ID
						where p.Governorate == governorate
						group m by new { governorate, m.Diagnosis } into diseaseGroup
						select new StatisticsHospitalVM
						{
							Governorate = diseaseGroup.Key.governorate,
							Diagnosis = diseaseGroup.Key.Diagnosis,
							DiseaseCount = diseaseGroup.Count()
						};

			return query.OrderByDescending(d => d.DiseaseCount).FirstOrDefault();
		}

		private StatisticsHospitalVM GetDeathCount()
		{
			var query = from m in context.MedicalRecords
						where m.Diagnosis.StartsWith("deceased by") && m.Diagnosis.Contains("cancer")
						select new StatisticsHospitalVM
						{
							DeathCount = m.Id
						};

			return new StatisticsHospitalVM
			{
				DeathCount = query.Count()
			};
		}

		private StatisticsHospitalVM GetAvgAgeByDiagnosis()
		{
			var query = from p in context.Patients
						join m in context.MedicalRecords on p.ID equals m.Patient_id
						group new { p, m } by m.Diagnosis into g
						select new DiagnosisAgeItem
						{
							Diagnosis = g.Key,
							AvgAge = g.Average(x => (DateTime.Now.Year - x.p.BDate.Year))
						};

			var viewModel = new StatisticsHospitalVM
			{
				AvgAgesByDiagnosis = query.ToList()
			};

			return viewModel;
		}

		private StatisticsHospitalVM GetDepartmentPatientCount()
		{
			var query = from d in context.Departments
						join s in context.Staffs on d.Id equals s.dept_id
						join m in context.MedicalRecords on s.ID equals m.Doctor_id
						join p in context.Patients on m.Patient_id equals p.ID
						group p by new { d.Id, d.Name } into g
						select new StatisticsHospitalVM
						{
							DepartmentName = g.Key.Name,
							PatientCount = g.Select(p => p.ID).Distinct().Count()
						};

			var departmentPatientCounts = query.OrderByDescending(x => x.PatientCount).ToList();

			var viewModel = new StatisticsHospitalVM
			{
				DepartmentName = departmentPatientCounts.FirstOrDefault()?.DepartmentName,
				PatientCount = departmentPatientCounts.FirstOrDefault().PatientCount
			};

			return viewModel;
		}
		private StatisticsHospitalVM GetMostCommonDiagnosis()
		{
			var query = from m in context.MedicalRecords
						join p in context.Patients on m.Patient_id equals p.ID
						group new { m, p } by new { m.Diagnosis, Month = m.StartDate.Month } into g
						orderby g.Count() descending
						select new StatisticsHospitalVM
						{
							Diagnosis = g.Key.Diagnosis,
							Month = g.Key.Month,
							DiseaseCount = g.Count()
						};

			var result = query.FirstOrDefault();

			return result;
		}
		public StatisticsHospitalVM GetTopTreatments()
		{
			var query = from m in context.MedicalRecords
						join p in context.Patients on m.Patient_id equals p.ID
						group m by m.Treatment into g
						orderby g.Count() descending
						select new TopTreatments
						{
							Treatment = g.Key,
							MedicalCount = g.Count()
						};

			var topTreatments = query.Take(10).ToList();

			var viewModel = new StatisticsHospitalVM
			{
				topTreatments = topTreatments
			};

			return viewModel;
		}
		private StatisticsHospitalVM GetDashboardStatistics()
		{
			var viewModel = new StatisticsHospitalVM
			{
				DepartmentCount = context.Departments.Count(),
				DoctorCount = context.Staffs.Count(s => s.Role == "Doctor"),
				NurseCount = context.Staffs.Count(s => s.Role == "Nurse"),
				PatientCount = context.Patients.Count()
			};

			return viewModel;
		}
	}
}

Hospital_Management_System/Views/Shared/_ALayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!---->
     <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<!-- Boxicons -->
	<link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
	<!-- My CSS -->
	<link rel="stylesheet" href="/css/style.css">

	<title>HMS</title>
</head>
<body>


	<!-- SIDEBAR -->
	<section id="sidebar">
		<a href="#" class="brand">
			<i class='bx bxs-smile'></i>
			<span class="text">HMS</span>
		</a>
		<ul class="side-menu top" style="padding:0px">
			<li >
				<a href="#">
					<i class='bx bxs-dashboard' ></i>
					<span class="text">Dashboard</span>
				</a>
			</li>
			<li >
				<a asp-action="Index" asp-controller="DoctorsManagment">
					<i class='bx' >
						<i class="fas fa-user-md"></i>
					</i>
					<span class="text">Doctor</span>
				</a>
			</li>
			<li>
				<a asp-action="Index" asp-controller="NursesManagment">
					<i class='bx ' >
						<i class="fas fa-user-nurse"></i>
					</i>
					<span class="text">Nurses</span>
				</a>
			</li>
			<li>
				<a asp-action="Index" asp-controller="Statistics">
					<i class='bx '>
						<i class="fa-solid fa-magnifying-glass-chart"></i>
					</i>
					<span class="text">Nurses</span>
				</a>
			</li>
		</ul>
		<ul class="side-menu">

			<li>
				<a asp-controller="Account" asp-action="Logout" class="logout" style="transform: translate(-2vw,20vh);">
					<i class='bx' >
						<i class="fa-solid fa-right-to-bracket"></i>
					</i>
					<span class="text">Logout</span>
				</a>
			</li>
		</ul>
	</section>
	<!-- SIDEBAR -->



	<!-- CONTENT -->
	<section id="content">
		<!-- NAVBAR -->
		<nav>
			<i class='bx bx-menu' ></i>

		</nav>
		<!-- NAVBAR -->

		<!-- MAIN -->
		<main>
			<div class="head-title">
				<div class="left">
					<h1>Dashboard</h1>
					<ul class="breadcrumb">
						<li>
							<a href="#">Dashboard</a>
						</li>
						<li><i class='bx bx-chevron-right' ></i></li>
						<li>
							<a class="active" href="#">Home</a>
						</li>
					</ul>
				</div>

			</div>

			
			<!--table for doctor-->
			<div>
				@RenderBody()
			</div>

		</main>
		<!-- MAIN -->
	</section>
	<!-- CONTENT -->
	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
 
  
    <link rel="stylesheet" href="/lib/bootstrap/dist/js/bootstrap.js">
 
	<script src="/js/script.js"></script>
</body>
</html>

<script>
	document.addEventListener('DOMContentLoaded', function () {
		var currentUrl = window.location.pathname;
		var menuLinks = document.querySelectorAll('#sidebar ul.side-menu a');

		menuLinks.forEach(function (link) {
			var linkUrl = link.getAttribute('href');
			if (currentUrl.endsWith(linkUrl)) {
				link.parentNode.classList.add('active');
			}
		});
	});
</script>
<style>
	#sidebar ul.side-menu li.active {
		color: blue;
	}

</style>

Hospital_Management_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--==================== UNICONS ====================-->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" />

    <!--==================== SWIPER CSS ====================-->
    <link rel="stylesheet" href="~/css/swiper-bundle.min.css" />

    <!--==================== CSS ====================-->
    <link rel="stylesheet" href="~/css/home-style.css" />
    <link rel="stylesheet" href="~/css/sign-in-style.css" />
    <link rel="stylesheet" href="~/css/register-style.css" />

    <!--=============== REMIXICONS ===============-->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/3.5.0/remixicon.css" />
    <script src="https://kit.fontawesome.com/64d58efce2.js"
            crossorigin="anonymous"></script>


    <!--==================== website-logo-And-title ====================-->
    <link rel="icon" type="image/x-icon" href="~/image/city-hospital.svg" />
    <title>SCI Hospital</title>
</head>
<body>
    <!--==================== HEADER ====================-->
    <header class="header" id="header">
        <nav class="nav container">
            <a href="#" class="nav__logo">SCI Hospital</a>

            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list grid">
                    <li class="nav__item">
                        <a href="@Url.Action("Index", "Home")" class="nav__link active-link">
                            <i class="uil uil-hospital-square-sign nav__icon"></i> Home

                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="#about" class="nav__link">
                            <i class="uil uil-hospital nav__icon"></i> About
                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="#services" class="nav__link">
                            <i class="uil uil-stethoscope-alt nav__icon"></i> Services
                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="@Url.Action("Login", "Account")" class="nav__link">
                            <i class="uil uil-sign-in-alt nav__icon"></i> Login
                        </a>
                    </li>
                    <li class="nav__item">
                        <a href="@Url.Action("Register", "Account")" class="nav__link">
                            <i class="uil uil-user-plus  nav__icon"></i> Register
                        </a>
                    </li>
                </ul>
                <i class="uil uil-times nav__close" id="nav-close"></i>
            </div>

            <div class="nav__btns">
                <!-- theme change button -->
                <i class="uil uil-moon change-theme" id="theme-button"></i>
                <div class="nav__toggle" id="nav-toggle">
                    <i class="uil uil-draggabledots"></i>
                </div>
            </div>
        </nav>
    </header>

    <!--==================== Main ====================-->
    @RenderBody()
    <!--==================== FOOTER ====================-->
    <footer class="footer">
        <div class="footer__bg">
            <div class="footer__container container grid">
                <div>
                    <h1 class="footer__title">SCI</h1>
                    <span class="footer__subtitle">
                        SCI Hospital provides progressive
                        and affordable healthcare, accessible online and online for everyone
                    </span>
                </div>

                <ul class="footer__links">
                    <li>
                        <a href="#home" class="footer__link">Home</a>
                    </li>
                    <li>
                        <a href="#services" class="footer__link">Services</a>
                    </li>
                    <li>
                        <a href="#about" class="footer__link">About</a>
                    </li>
                </ul>
                <div class="footer__socials">
                    <a href="https://github.com/Adelkazzaz/Hospital_Management_System" target="_blank" class="footer__social">
                        <i class="uil uil-facebook-f"></i>
                    </a>
                    <a href="https://github.com/Adelkazzaz/Hospital_Management_System" target="_blank" class="footer__social">
                        <i class="uil uil-instagram"></i>
                    </a>
                    <a href="https://github.com/Adelkazzaz/Hospital_Management_System" target="_blank" class="footer__social">
                        <i class="ri-twitter-x-fill"></i>
                    </a>
                </div>
            </div>
            <p class="footer__copy">&#169; SCI Hospital 2023. All rights reserved.</p>
        </div>
    </footer>

    <!--==================== SCROLL TOP ====================-->
    <a href="#" class="scrollup" id="scroll-up">
        <i class="uil uil-arrow-up scrollup__icon"></i>
    </a>

    <!--==================== SWIPER JS ====================-->
    <script src="~/js/swiper-bundle.min.js"></script>

    <!--==================== MAIN JS ====================-->
    <script src="~/js/home-main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>