Hospital_Management_System/Controllers/DoctorsManagmentController.cs
using demo.Models;
using Hospital_Management_System.Models;
using Hospital_Management_System.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MySqlConnector;
using System.Data;
using System.Linq;
using System.Numerics;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Hospital_Management_System.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DoctorsManagmentController : Controller
    {
        HMSEntites _context = new HMSEntites();

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInMAnager;

        public DoctorsManagmentController
            (UserManager<ApplicationUser> _UserManager,
            SignInManager<ApplicationUser> _SignInMAnager)
        {
            userManager = _UserManager;
            signInMAnager = _SignInMAnager;
        }

        public ActionResult Index()
        {
            //full name and department --details->(update-delete)
            var data =
       from s in _context.Staffs
       join dept in _context.Departments on s.dept_id equals dept.Id
       join d in _context.Doctors on s.ID equals d.Id
       select new StaffVM
       {
           Name = s.FullName,
           DeptName = dept.Name,
           Id = d.Id,
       };
            List<StaffVM> result = data.ToList();

            return View("Index", result);
        }
        public ActionResult DoctorDetails(int id)
        {

            var data =
          from s in _context.Staffs
          join d in _context.Doctors
          on s.ID equals id
          join dept in _context.Departments
          on s.dept_id equals dept.Id
                  where d.Id == id
          select new StaffDetailsVM
          {
              Id = id,
              FullName = s.FullName,
              Gender = s.Gender,
              BDate = s.BDate,
              Phone = s.Phone,
              Role = s.Role,
              UserName = s.UserName,
              Specialization = d.Specialization,
              DepartmentName = dept.Name,
              Qualifications = s.Qualifications,
              Governorate = s.Governorate,
              City = s.City
          };
            return View("DoctorDetails", data.ToList().FirstOrDefault());
        }
        public IActionResult AddDoctor()
        {
            ViewBag.departments= _context.Departments.ToList();

			return View("AddDoctor"); 

        }

        //Save doctor in Database 
        [HttpPost]
        public async Task<IActionResult> SaveDoctor(AddDoctorVM model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("AddDoctor");
            }

            int docID = GetNextDoctorId();

            var staff = new Staff
            {
                FullName = model.FullName,
                Gender = model.Gender,
                BDate = model.BDate,
                Phone = model.Phone,
                UserName = model.UserName,
                Password = userManager.PasswordHasher.HashPassword(null, model.Password),
                Salary = model.Salary,
                Role = model.Role,
                Qualifications = model.Qualifications,
                dept_id = model.DeptId,
                hospital_id = 1,
                Governorate = model.Governorate,
                City = model.City,
                Country = model.Country,
                Shift = model.Shift,
                ID = docID
            };

            var doctor = new Doctor
            {
                Id = docID,
                Specialization = model.Specialization,
                Staff = staff
            };

            ApplicationUser newDoctorUser = new ApplicationUser
            {
                FullName = model.FullName,
                Gender = model.Gender,
                BDate = model.BDate,
                PhoneNumber = model.PhoneNumber,
                Country = model.Country,
                Governorate = model.Governorate,
                City = model.City,
                UserName = model.UserName,
                Blood_Type = "A",
                PasswordHash = userManager.PasswordHasher.HashPassword(null, model.Password),
            };

            // Check if the username already exists
            if (await userManager.FindByNameAsync(model.UserName) != null)
            {
                ModelState.AddModelError("", "Username is already taken.");
                return View("AddDoctor", model);
            }

            try
            {
                _context.Users.Add(newDoctorUser);
                _context.Doctors.Add(doctor);
                _context.Staffs.Add(staff);
                _context.SaveChanges();

                await userManager.AddToRoleAsync(newDoctorUser, "Doctor");
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while saving the data.");
                return RedirectToAction("Index");

            }

            return RedirectToAction("Index");
        }


        public ActionResult DeleteDoctor(int id)
        {

                try
                {
                    var doctorToDelete = _context.Doctors.FirstOrDefault(d => d.Id == id);

                if (doctorToDelete == null)
                    {
                        ViewBag.ErrorMessage = "Doctor not found.";
                        return View("Error");
                    }

                    _context.Doctors.Remove(doctorToDelete);
                    _context.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {

                    ViewBag.ErrorMessage = ex.Message;
                    return View("Error");
                }
            
        }



		public IActionResult EditDoctor(int id)
		{
			var doctor = _context.Doctors
								.Include(d => d.Staff)
								.Include(d => d.Staff.Department)
								.FirstOrDefault(d => d.Id == id);

			if (doctor == null)
			{
				ViewBag.ErrorMessage = "Doctor not found.";
				return View("Error");
			}

			var editDoctorVM = new EditDoctorVM
			{
				Id = doctor.Id,
				FullName = doctor.Staff.FullName,
				Gender = doctor.Staff.Gender,
				BDate = doctor.Staff.BDate,
				Phone = doctor.Staff.Phone,
				UserName = doctor.Staff.UserName,
				Password = doctor.Staff.Password,
				Salary = doctor.Staff.Salary,
				Role = doctor.Staff.Role,
				Qualifications = doctor.Staff.Qualifications,
				DeptId = doctor.Staff.dept_id,
				Governorate = doctor.Staff.Governorate,
				City = doctor.Staff.City,
				Specialization = doctor.Specialization,
				Shift = doctor.Staff.Shift,
				Country = doctor.Staff.Country
			};

			ViewBag.Departments = _context.Departments.ToList();

			return View("EditDoctor", editDoctorVM);
		}

		[HttpPost]
		public IActionResult EditDoctor(int id, EditDoctorVM editedDoctor)
		{

			if (!ModelState.IsValid)
			{
				return RedirectToAction("AddDoctor");
			}

			var existingDoctor = _context.Doctors
										.Include(d => d.Staff)
										.FirstOrDefault(d => d.Id == id);

			if (existingDoctor == null)
			{
				ViewBag.ErrorMessage = "Doctor not found.";
				return View("Error");
			}

			existingDoctor.Staff.FullName = editedDoctor.FullName;
			existingDoctor.Staff.Gender = editedDoctor.Gender;
			existingDoctor.Staff.BDate = editedDoctor.BDate;
			existingDoctor.Staff.Phone = editedDoctor.Phone;
			existingDoctor.Staff.UserName = editedDoctor.UserName;
			existingDoctor.Staff.Password = editedDoctor.Password;
			existingDoctor.Staff.Salary = editedDoctor.Salary;
			existingDoctor.Staff.Role = editedDoctor.Role;
			existingDoctor.Staff.Qualifications = editedDoctor.Qualifications;
			existingDoctor.Staff.dept_id = editedDoctor.DeptId;
			existingDoctor.Staff.Governorate = editedDoctor.Governorate;
			existingDoctor.Staff.City = editedDoctor.City;
			existingDoctor.Specialization = editedDoctor.Specialization;
			existingDoctor.Staff.Shift = editedDoctor.Shift;
			existingDoctor.Staff.Country = editedDoctor.Country;

			try
			{
				_context.SaveChanges();
			}
			catch (Exception)
			{
				ModelState.AddModelError(string.Empty, "An error occurred while saving the data.");
				ViewBag.Departments = _context.Departments.ToList();
				return View("EditDoctor", editedDoctor);
			}

			return RedirectToAction("Index");
		}

        private int GetNextDoctorId()
        {
            // return max id and increment by 1
            return _context.Doctors.Max(p => p.Id) + 1;
        }


    }
}

Hospital_Management_System/Views/DoctorsManagment/AddDoctor.cshtml
@model AddDoctorVM

@{
    Layout = null; // or Layout = "";


    SelectList listItems = new SelectList(ViewBag.departments, "Id", "Name");

}


<head>
    <title>Add Doctor </title>
    <link rel="stylesheet" href="/css/doc-register-style.css" />
    @* <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css *@" 
</head>
<body>
    <section class="container">
        <header>Add Doctor Form</header>
        <form asp-controller="DoctorsManagment" asp-action="SaveDoctor" method="post" class="form">
            <!----------------------------------------------------------------------------------------------------->
            <input type="hidden" asp-for="Shift" value="Day" />
            <input type="hidden" asp-for="Country" value="Egypt" />

            <div class="input-box ">
                <div class="column">
                    <div class="col">
                        <label asp-for="FullName">Full Name</label>
                        <input class="form-control" asp-for="FullName" placeholder="Enter Your Full Name" />
                        <span asp-validation-for="FullName" class="text-danger"></span>

                    </div>
                    <div class="col">
                        <label asp-for="Specialization">Specialization</label>
                        <input class="form-control" asp-for="Specialization" placeholder="Enter The Specialization" />
                        <span asp-validation-for="Specialization" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="input-box ">
                <div class="column">
                    <div class="col">
                        <label asp-for="Qualifications">Degree &#160;</label>
                        <input class="form-control" asp-for="Qualifications" placeholder="Qualifications" />
                        <span asp-validation-for="Qualifications" class="text-danger"></span>

                    </div>
                    <div class="col">
                        <label asp-for="Role">Job Title</label>
                        <input class="form-control" asp-for="Role" placeholder="Enter The Job Title" />
                        <span asp-validation-for="Role" class="text-danger"></span>

                    </div>
                </div>
            </div>
            <div class="input-box ">
                <div class="column">
                    <div class="col">
                        <label asp-for="UserName">Doctor UserName</label>
                        <input class="form-control" asp-for="UserName" placeholder="Enter Doctor UserName" />
                        <span asp-validation-for="UserName" class="text-danger"></span>

                    </div>
                    <div class="col">
                        <label asp-for="Salary">Doctor Salary</label>
                        <input class="form-control" asp-for="Salary" placeholder="Enter Doctor Salary " />
                        <span asp-validation-for="Salary" class="text-danger"></span>

                    </div>
                </div>
            </div>

            </div>
            </div>
            <!----------------------------------------------------------------------------------------------------->

            <div class="column">
                <div class="input-box PhoneNumber">
                    <label asp-for="Phone">Phone Number</label>
                    <input class="form-control" asp-for="Phone" placeholder="Enter Doctor Phone">
                    <span asp-validation-for="Phone" class="text-danger"></span>

                </div>
                <div class="input-box BirthDate">
                    <label asp-for="BDate">Doctor Birth Date</label>
                    <input type="date" class="form-control" asp-for="BDate" placeholder="Enter Doctor Birth Date " />
                    <span asp-validation-for="BDate" class="text-danger"></span>
                </div>

            </div>
            <div class="column">
                <div class="input-box PhoneNumber">
                    <label asp-for="Governorate">Enter Governorate</label>
                    <input class="form-control" asp-for="Governorate" placeholder="Enter Governorate" />
                    <span asp-validation-for="Governorate" class="text-danger"></span>

                </div>
                <div class="input-box PhoneNumber">
                    <label asp-for="City">Enter City</label>
                    <input class="form-control" asp-for="City" placeholder="Enter City" />
                    <span asp-validation-for="City" class="text-danger"></span>


                </div>
            </div>
            </div>

            <div class="input-box address">
                <label asp-for="DeptId">Department</label>
                <div class="column">
                    <div class="country-select-box select-box">
                        <select class="form-control" asp-for="DeptId" asp-items="@listItems" ></select>
                        <span asp-validation-for="DeptId" class="text-danger"></span>

                    </div>
                </div>
            </div>
            <div class="input-box address ">
                <label asp-for="Password">Enter Password</label>
                <div class="column">
                    <input class="form-control" asp-for="Password" placeholder="Enter Password" />
              
                </div>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="input-box address ">
                <label asp-for="ConfirmPassword">Renter Password</label>
                <div class="column">
                    <input class="form-control" asp-for="ConfirmPassword" placeholder="Renter Password" />

                </div>
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="gender-box">
                <h3>Gender</h3>
                <div class="gender-option">
                    <div class="gender">
                        <input class="form-check-input" type="radio" asp-for="Gender" value="Male" />
                        <label asp-for="Gender" class="control-label">Male</label>

                    </div>
                    <div class="gender">
                        <input class="form-check-input" type="radio" asp-for="Gender" value="Female" />
                        <label asp-for="Gender" class="control-label">Female</label>
                        <span asp-validation-for="Gender" class="text-danger"></span>

                    </div>
                </div>
            </div>
            <button>Save</button>
        </form>
    </section>
</body>
<style>
    span {
        color: red;
    }
</style>


@* <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

Hospital_Management_System/Views/DoctorsManagment/DoctorDetails.cshtml
@model StaffDetailsVM

@{
    Layout = null;

}
<link rel="stylesheet" href="/css/StaffDetailsStyle.css" />
<link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css">

    <section class="medical-records">

        <div id="medicalRecordsContainer">
            <a class="btn btn-primary m-2" asp-action="Index">Go Back</a>
            <div class="medical-card">
                <table>
                    <tr>
                        <th>Full Name</th>
                        <td>@Model.FullName</td>
                    </tr>
                    <tr>
                        <th>DepartmentName</th>
                        <td>@Model.DepartmentName</td>
                    </tr>
                    <tr>
                        <th>Specialization</th>
                        <td>@Model.Specialization</td>
                    </tr>
                    <tr>
                        <th>Qualifications</th>
                        <td>@Model.Qualifications</td>
                    </tr>
                    <tr>
                        <th>Role</th>
                        <td>@Model.Role</td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td>@Model.Phone</td>
                    </tr>
                    <tr>
                        <th>UserName</th>
                        <td>@Model.UserName</td>
                    </tr>
                    <tr>
                        <th>Birth Date</th>
                        <td>@Model.BDate</td>
                    </tr>
                    <tr>
                        <th>Gender</th>
                        <td>@Model.Gender</td>
                    </tr>
                    <tr>
                        <th>Governorate</th>
                        <td>@Model.Governorate</td>
                    </tr>
                    <tr>
                        <th>City</th>
                        <td>@Model.City</td>
                    </tr>

                </table>
                <a class="btn btn-danger m-2" asp-action="DeleteDoctor" asp-controller="DoctorsManagment" asp-route-id="@Model.Id">Delete</a>



            </div>


        </div>

    </section>

Hospital_Management_System/Views/DoctorsManagment/Edit.cshtml
@* @model AddDoctorVM

@{
    Layout = null; // or Layout = "";
    var DepartmentList = new SelectList(ViewBag.dept, "Id", "Name");
}


<head>
    <title>Edit Doctor </title>
    <link rel="stylesheet" href="/css/register-style.css" />
</head>
<body>
    <section class="container">
        <header>Edit Doctor Form</header>
        <form asp-action="SaveEdit" asp-controller="DoctorsManagment" asp-route-id="@Model.Id" method="post" class="form">
            <!----------------------------------------------------------------------------------------------------->

            <div class="input-box ">
                <div class="column">
                    <div class="col">
                        <label asp-for="FullName">Full Name</label>
                        <input class="form-control" asp-for="FullName" placeholder="Enter Your Full Name" value="@Model.FullName" required />
                        <span asp-validation-for="FullName" class="text-danger"></span>

                    </div>
                    <div class="col">
                        <label asp-for="Specialization">Specialization</label>
                        <input class="form-control" asp-for="Specialization" placeholder="Enter The Specialization" value="@Model.Specialization" required />
                        <span asp-validation-for="Specialization" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="input-box ">
                <div class="column">
                    <div class="col">
                        <label asp-for="Qualifications">Degree &#160;</label>
                        <input class="form-control" asp-for="Qualifications" placeholder="Qualifications" value="@Model.Qualifications" required />
                        <span asp-validation-for="Qualifications" class="text-danger"></span>

                    </div>
                    <div class="col">
                        <label asp-for="Role">Job Title</label>
                        <input class="form-control" asp-for="Role" placeholder="Enter The Job Title" value="@Model.Role" required />
                        <span asp-validation-for="Role" class="text-danger"></span>

                    </div>
                </div>
            </div>
            <div class="input-box ">
                <div class="column">
                    <div class="col">
                        <label asp-for="Email">Doctor Email</label>
                        <input class="form-control" asp-for="Email" placeholder="Enter Doctor Email" value="@Model.Email" required />
                        <span asp-validation-for="Email" class="text-danger"></span>

                    </div>
                    <div class="col">
                        <label asp-for="Salary">Doctor Salary</label>
                        <input class="form-control" asp-for="Salary" placeholder="Enter Doctor Salary " value="@Model.Salary" required />
                        <span asp-validation-for="Salary" class="text-danger"></span>

                    </div>
                </div>
            </div>
            <div class="input-box ">
                <div class="column">
                    <div class="col">
                        <label asp-for="Password">Enter Password</label>
                        <input class="form-control" asp-for="Password" placeholder="Enter Password" vlaue="@Model.Password" />
                        <span asp-validation-for="Password" class="text-danger"></span>

                    </div>
                    <div class="col">
                        <label class="repass">Confirm Password</label>
                        <input class="form-control" class="repass" placeholder="Confirm Password" />
                        <span class="text-danger"></span>

                    </div>
                </div>
            </div>
            <!----------------------------------------------------------------------------------------------------->

            <div class="column">
                <div class="input-box PhoneNumber">
                    <label asp-for="Phone">Phone Number</label>
                    <input class="form-control" asp-for="Phone" placeholder="Enter Doctor Phone" value="@Model.Phone" required>
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="input-box BirthDate">
                    <label asp-for="BDate">Doctor Birth Date</label>
                    <input type="date" class="form-control" asp-for="BDate" placeholder="Enter Doctor Birth Date " value="@Model.BDate" required />
                    <span asp-validation-for="BDate" class="text-danger"></span>
                </div>

            </div>
            <div class="column">
                <div class="input-box PhoneNumber">
                    <label asp-for="Governorate">Enter Governorate</label>
                    <input class="form-control" asp-for="Governorate" placeholder="Enter Governorate" value="@Model.Governorate" />
                    <span asp-validation-for="Governorate" class="text-danger"></span>

                </div>
                <div class="input-box PhoneNumber">
                    <label asp-for="City">Enter City</label>
                    <input class="form-control" asp-for="City" placeholder="Enter City" value="@Model.City" />
                    <span asp-validation-for="City" class="text-danger"></span>
                    <span asp-validation-for="City" class="text-danger"></span>

                </div>
            </div>
            </div>
            <div class="gender-box">
                <h3>Gender</h3>
                <div class="gender-option">
                    <div class="gender">
                        <input class="form-check-input" type="radio" asp-for="Gender" value="@Model.Gender" />
                        <label asp-for="Gender" class="control-label">Male</label>
                    </div>
                    <div class="gender">
                        <input class="form-check-input" type="radio" asp-for="Gender" value="@Model.Gender" />
                        <label asp-for="Gender" class="control-label">Female</label>
                        <span asp-validation-for="Gender" class="text-danger"></span>

                    </div>
                </div>
            </div>
            <div class="input-box address">
                           <label asp-for="DeptId">Department</label>
                <div class="column">
                <div class="country-select-box select-box">
                        <select class="form-control" asp-for="DeptId" asp-items="@DepartmentList" value="@Model.DepartmentName"></select>
                        <span asp-validation-for="DeptId" class="text-danger"></span>
                    </div>
                </div> 

                <button>Save</button>
        </form>
    </section>
</body>


 *@

Hospital_Management_System/Views/DoctorsManagment/Index.cshtml
@using Hospital_Management_System.ViewModel;
@model List<StaffVM>
@{
	Layout = "_ALayout";
}
 

	<link rel="stylesheet" href="/css/style.css" />
	<div class="table-data">
		<div class="order">
			<div class="head">
				<h3>Doctors</h3>

				<a class="btn btn-primary m-2" asp-action="AddDoctor">Add Doctor</a>
			</div>
			<table>
				<thead>
					<tr>
						<th>Doctor Full Name</th>
						<th>Department</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var doctor in Model)
					{
						<tr>
							<td>
								<img src="https://cdn-icons-png.flaticon.com/512/3774/3774293.png">
								<p>@doctor.Name</p>
							</td>
							<td>@doctor.DeptName</td>
							<td><a asp-action="DoctorDetails" asp-controller="DoctorsManagment" asp-route-id="@doctor.Id" class="btn btn-info">Details</a> </td>
							<td><a asp-action="EditDoctor" asp-controller="DoctorsManagment" asp-route-id="@doctor.Id" class="btn btn-primary" >Edit</a> </td>

						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>